<?php
/**
*
* @ This file is created by Decodeby.US
* @ deZender Public (PHP5 Decompiler)
*
* @	Version			:	1.0.0.0
* @	Author			:	Ps2Gamer & Cyko
* @	Release on		:	30.05.2011
* @	Official site	:	http://decodeby.us
*
*/

require_once( LANG_UI_PATH."custbuilds.php" );
$buildingMetadata = $this->gameMetadata['items'][$this->buildProperties['building']['item_id']];
$bLevel = $this->buildings[$this->buildingIndex]['level'];
 $this->selectedTabIndex = isset( $_GET['t'] ) && is_numeric( $_GET['t'] ) && 0 <= intval( $_GET['t'] ) && intval( $_GET['t'] ) <= 3 ? intval( $_GET['t'] ) : 0;
        
?>
<div id="textmenu">
   <a href="build.php?id=<?php echo $this->buildingIndex; ?>" <?php
        if ( $this->selectedTabIndex == 0 )
{
    echo " class=\"selected\"";
}
       

?>
    ">Own artefacts</a>
         
 | <a href="build.php?id=<?php echo $this->buildingIndex; ?>&t=2" <?php

       if ( $this->selectedTabIndex == 2 )
{
    echo " class=\"selected\"";
}

?>">Small artefacts</a>

 | <a href="build.php?id=<?php echo $this->buildingIndex; ?>&t=3" <?php

        if ( $this->selectedTabIndex == 3 )
{
    echo " class=\"selected\"";
}
?>">Large artefacts</a>
</div> 
<?php
if ( $this->selectedTabIndex == 0 )
{
?>
<div class="gid27">
<body>
    <table id="own" cellpadding="1" cellspacing="1">
        <thead>
            <tr>
                <th colspan="4">Own artefacts</th>
            </tr>
            <tr>
                <td></td>
                <td>Name</td>
                <td>Village</td>
                <td>Conquered</td>
            </tr>
        </thead>

        <tbody>
            <tr>

<td colspan="4" class="none">You do not own any artefacts.</td>

            </tr>
        </tbody>
    </table>

    <table id="near" cellpadding="1" cellspacing="1">
        <thead>
            <tr>
                <th colspan="4">Artefacts in your area</th>
            </tr>

            <tr>
                <td></td>

                <td>Name</td>

                <td>Player</td>

                <td>Distance</td>
            </tr>
        </thead>

        <tbody>

        </tbody>
    </table>
</div>
<?php

}else if ( $this->selectedTabIndex == 2 )
{
?>

        <table id="show_artefacts" cellpadding="1" cellspacing="1">
            <thead>
                <tr>
                    <th colspan="4">Small artefacts</th>
                </tr>
                <tr>
                    <td></td>
                    <td>Name</td>
                    <td>Player</td>
                    <td>Alliance</td>
                </tr>
            </thead>
            <tbody>

           
     
        </tbody></table>
        
     
        

<?php    
}else if ( $this->selectedTabIndex == 3 )
{
?>
   <table id="show_artefacts" cellpadding="1" cellspacing="1">
            <thead>
                <tr>
                    <th colspan="4">Large artefacts</th>
                </tr>
                <tr>
                    <td></td>
                    <td>Name</td>
                    <td>Player</td>
                    <td>Alliance</td>
                </tr>
            </thead>
            <tbody>

         
     
        </tbody></table>
<?php   
}
?>

