<?php
#################################################################################
##                                                                             ##
##              -= YOU MUST NOT REMOVE OR CHANGE THIS NOTICE =-                ##
##                                                                             ##
## --------------------------------------------------------------------------- ##
##                                                                             ##
##  Project:       TravianZ                                                    ##
##  Filename:      footer.phtml                                                ##
##  Developed by:  Advocaite                                                   ##
##  License:       Creative Commons BY-NC-SA 3.0                               ##
##  Copyright:     Advocaite (c) 2011 - All rights reserved                    ##
##                                                                             ##
#################################################################################

require_once( LANG_UI_PATH."footer.php" );
?>

<ul class="menu menu2">
    <li><a href="index.php"><?php echo LANGUI_FOOTER_MAIN;?></a></li>
    <li><a href="manual.php"><?php echo LANGUI_FOOTER_MANUAL;?></a></li>
    <li><a href="training.php"><?php echo LANGUI_FOOTER_TRAINING;?></a></li>
    <li><a href="http://www.ragezone.com" target="_blank">Copyright &copy; TravianX</a></li>
</ul>
