<?php
require_once( LANG_UI_PATH."changes.php" );
echo "<h1 align=\"center\">";
echo LANGUI_CHANGES_T1;
echo "</h1>\r\n<table cellpadding=\"1\" cellspacing=\"1\" id=\"links\">\r\n\t<thead>\r\n\t\t<tr>\r\n\t\t\t<th colspan=\"2\">";
echo LANGUI_CHANGES_T2;
echo "</th>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>";
echo LANGUI_CHANGES_T3;
echo "</td>\r\n</tr>\r\n\t</thead>\r\n\t<tbody>\r\n<tr><td>   ";
echo LANGUI_CHANGES_D1;
echo "\r\n\t</tbody>\r\n</table>\r\n";
echo "</h1>\r\n<table cellpadding=\"1\" cellspacing=\"1\" id=\"links\">\r\n\t<thead>\r\n\t\t<tr>\r\n\t\t\t<th colspan=\"2\">";
echo LANGUI_CHANGES_T4;
echo "</th>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>";
echo LANGUI_CHANGES_T5;
echo "</td>\r\n</tr>\r\n\t</thead>\r\n\t<tbody>\r\n<tr><td>   ";
echo LANGUI_CHANGES_D2;
echo "\r\n\t</tbody>\r\n</table>\r\n";

?>
