<?php
/**
*
* @ This file is created by Decodeby.US
* @ deZender Public (PHP5 Decompiler)
*
* @	Version			:	1.0.0.0
* @	Author			:	Ps2Gamer & Cyko
* @	Release on		:	30.05.2011
* @	Official site	:	http://decodeby.us
*
*/

require_once( LANG_UI_PATH."logout.php" );
echo "<h1>";
echo LANGUI_LOGOUT_T1;
echo "</h1>\r\n<img class=\"roman\" src=\"assets/x.gif\" alt=\"\">\r\n<p>";
echo LANGUI_LOGOUT_T2;
echo "</p>\r\n<p></p>\r\n\r\n<p>";
echo LANGUI_LOGOUT_T3;
echo "</p><br>\r\n<a href=\"index.php?dcookie\">";
echo LANGUI_LOGOUT_T4;
echo "</a>\r\n<p></p>";
?>
