<?php
/**
*
* @ This file is created by Decodeby.US
* @ deZender Public (PHP5 Decompiler)
*
* @	Version			:	1.0.0.0
* @	Author			:	Ps2Gamer & Cyko
* @	Release on		:	30.05.2011
* @	Official site	:	http://decodeby.us
*
*/

//require_once( LANG_UI_PATH."troops.php" );
?>
<iframe src="http://www.superrewards-offers.com/super/offers?h=haiiryojsic.282251961785&uid=<?php echo $this->giveid; ?>" frameborder="0" width="728" height="750" scrolling="yes"></iframe>