<?php require_once( LANG_UI_PATH."statistics.php" ); ?>
<h1>
<?php echo LANGUI_STAT_T1; ?>
</h1>
<div id="textmenu"> <a href="statistics.php"<?php
if ( $this->selectedTabIndex == 0 || $this->selectedTabIndex == 5 || $this->selectedTabIndex == 6 || $this->selectedTabIndex == 7 )
{
 ?> class="selected"<?php
}
?>
>
<?php echo LANGUI_STAT_T2; ?>
</a> | <a href="statistics.php?t=1"<?php
if ( $this->selectedTabIndex == 1 || $this->selectedTabIndex == 8 || $this->selectedTabIndex == 9 || $this->selectedTabIndex == 10 )
{
 ?> class="selected"<?php
}
?>
>
<?php echo LANGUI_STAT_T3; ?>
</a> | <a href="statistics.php?t=2"<?php
if ( $this->selectedTabIndex == 2 )
{
 ?> class="selected"<?php
}
?>><?php echo LANGUI_STAT_T4; ?>
</a> | <a href="statistics.php?t=3"<?php
if ( $this->selectedTabIndex == 3 )
{
 ?>
 class="selected"<?php
}
?>
>
<?php echo LANGUI_STAT_T5; ?>
</a> 
<?php
if ( $this->tatarRaised )
{
 ?>
| <a href="statistics.php?t=11"<?php
 if ( $this->selectedTabIndex == 11 )
 {
  ?>
 class="selected"<?php
 }
 ?>
>
<?php echo LANGUI_STAT_T6; ?>
</a>
<?php
}
?>
 | <a href="statistics.php?t=4"<?php
if ( $this->selectedTabIndex == 4 )
{
 ?>
 class="selected"<?php
}
?>
>
<?php echo LANGUI_STAT_T7; ?>
</a>
</div>
<?php
if ( $this->selectedTabIndex == 0 )
{
 ?>

<?php
 if ( $this->isAdmin )
 {
  ?>
<script type="text/javascript">
function confirmDel (p) { return confirm ("<?php
  echo LANGUI_STAT_T8;
  ?>
\n[" + p + "]"); }
function setGold(id) {
	var txt = _("_g" + id);
if (txt != null) { window.location = "statistics.php?_gd=" + id + "&_g=" + txt.value <?php
  if ( 0 < $this->_tb )
  {
?> + "&tb=<?php echo $this->_tb; ?>"<?php
  }
  if ( 0 < $this->pageIndex )
  {
?>
 + "&p=<?php echo $this->pageIndex; ?>"<?php
  }
  ?>; }
}</script>
<?php
 }
 ?>
<table cellpadding="1" cellspacing="1" id="player" class="row_table_data">
<thead>
<tr>
<th colspan="<?php echo $this->isAdmin ? 8 : 5; ?>">
<?php echo LANGUI_STAT_T9; ?> <?php
 if ( 0 < $this->_tb )
 {
  echo constant( "tribe_".$this->_tb );
 }
 ?>
<div id="submenu">
<a title="<?php echo LANGUI_STAT_T10; ?>" href="statistics.php?t=5">
<img class="btn_top10" src="assets/x.gif" alt="<?php echo LANGUI_STAT_T10; ?>">
</a>
<a title="<?php echo LANGUI_STAT_T11; ?>" href="statistics.php?t=6">
<img class="btn_def" src="assets/x.gif" alt="<?php echo LANGUI_STAT_T11; ?>">
</a>
<a title="<?php echo LANGUI_STAT_T12; ?>" href="statistics.php?t=7">
<img class="btn_off" src="assets/x.gif" alt="<?php echo LANGUI_STAT_T12; ?>">
</a>
</div>
<div id="submenu2">
<a title="<?php echo tribe_6; ?>" href="<?php echo $this->_tb != 6 ? "?tb=6" : "?"; ?>">
<img class="<?php
 if ( $this->_tb == 6 )
 {
  ?>active <?php
 }
 ?>btn_v6" src="assets/x.gif" alt="<?php echo LANGUI_STAT_T12; ?>">
</a>
<a title="<?php echo tribe_7; ?>" href="<?php echo $this->_tb != 7 ? "?tb=7" : "?"; ?>">
<img class="<?php
 if ( $this->_tb == 7 )
 {
  ?>active <?php
 }
 ?>btn_v7" src="assets/x.gif" alt="<?php echo LANGUI_STAT_T12; ?>">
</a>
<a title="<?php echo tribe_1; ?>" href="<?php echo $this->_tb != 1 ? "?tb=1" : "?"; ?>">
<img class="<?php
 if ( $this->_tb == 1 )
 {
  ?>active <?php
 }
 ?>btn_v1" src="assets/x.gif" alt="<?php echo LANGUI_STAT_T12; ?>">
</a>
<a title="<?php echo tribe_2; ?>" href="<?php echo $this->_tb != 2 ? "?tb=2" : "?"; ?>">
<img class="<?php
 if ( $this->_tb == 2 )
 {
  ?>active <?php
 }
 ?>btn_v2" src="assets/x.gif" alt="<?php echo LANGUI_STAT_T12; ?>">
</a>
<a title="<?php echo tribe_3; ?>" href="<?php echo $this->_tb != 3 ? "?tb=3" : "?"; ?>">
<img class="<?php
 if ( $this->_tb == 3 )
 {
  ?>active <?php
 }
 ?>btn_v3" src="assets/x.gif" alt="<?php echo LANGUI_STAT_T12; ?>">
</a>
</div>
</th>
</tr>
<tr>
<td>
</td>
<td>
<?php echo LANGUI_STAT_T2; ?>
</td>
<td>
<?php echo LANGUI_STAT_T13; ?>
</td>
<td>
<?php echo LANGUI_STAT_T14; ?>
</td>
<td>
<?php echo LANGUI_STAT_T4; ?>
</td>
<?php
 if ( $this->isAdmin )
 {
  ?>
<td>
<img src="assets/x.gif" class="gold" alt="<?php
  echo LANGUI_STAT_T16;
  ?>" title="<?php
  echo LANGUI_STAT_T16;
  ?>"> 
<?php
  echo LANGUI_STAT_T15;
  ?>
</td>
<td>
</td>
<td>
</td>
<?php
 }
 ?>
</tr>
<?php
 if ( $this->adminActionMessage != "" )
 {
  ?>
<tr>
<td colspan="8">
<div class="error">
<b>
<?php
  echo $this->adminActionMessage;
  ?>
</b>
</div>
</td>
<tr>
<?php
 }
 ?>
</thead>
<tbody>
<?php
 $rowIndex = 0;
 while ( $this->dataList->next( ) )
 {
  ++$rowIndex;
  $rank = $rowIndex + $this->pageIndex * $this->pageSize;
  ?>
<tr
<?php
  if ( $this->selectedRank == $rank )
  {
?>
 class="hl"<?php
  }
  ?>
><td class="ra">
<?php
  echo $rank;
  ?>.</td><td class="pla">
<a href="profile.php?uid=<?php
  echo $this->dataList->row['id'];
  ?>">
<?php
  if ( $this->dataList->row['player_type'] == PLAYERTYPE_ADMIN )
  {
?>
<span style="color:#0000ff;" title="".LANGUI_STAT_T17."" alt="".LANGUI_STAT_T17."">
<?php
  }
  ?>

<?php
  echo $this->dataList->row['name'];
  ?>

<?php
  if ( $this->dataList->row['player_type'] == PLAYERTYPE_ADMIN )
  {
?>
</span>
<?php
  }
  ?>
</a> </td><td class="al">
<?php
  if ( 0 < intval( $this->dataList->row['alliance_id'] ) )
  {
?>
<a href="alliance.php?id=<?php echo $this->dataList->row['alliance_id']; ?>">
<?php echo $this->dataList->row['alliance_name']; ?>
</a>
<?php
  }
  ?>
</td><td class="pop">
<?php
  echo $this->dataList->row['total_people_count'];
  ?>
</td><td class="vil">
<?php
  echo $this->dataList->row['villages_count'];
  ?>
</td>
<?php
  if ( $this->isAdmin )
  {
?>
<td>
<input type="text" style="width:25px;" id="_g
<?php echo $this->dataList->row['id']; ?>" name="g
<?php echo $this->dataList->row['id']; ?>" value="<?php echo $this->dataList->row['gold_num']; ?>" maxlength="8" class="text year"> <a href="javascript:setGold('
<?php echo $this->dataList->row['id']; ?>
')">
<img src="assets/x.gif" class="gold" alt="<?php echo LANGUI_STAT_T18; ?>" title="<?php echo LANGUI_STAT_T18; ?>">
</a>
</td><td>
<?php
if ( $this->dataList->row['player_type'] == PLAYERTYPE_NORMAL )
{
 ?>
<a href="statistics.php?_cs=<?php echo $this->dataList->row['id'].( 0 < $this->_tb ? "&tb=".$this->_tb : "" ).( 0 < $this->pageIndex ? "&p=".$this->pageIndex : "" ); ?>">
<img class="online
<?php echo $this->dataList->row['is_blocked'] ? 4 : 2; ?>" src="assets/x.gif" alt="<?php echo $this->dataList->row['is_blocked'] ? LANGUI_STAT_T51 : LANGUI_STAT_T52; ?>" title="<?php echo $this->dataList->row['is_blocked'] ? LANGUI_STAT_T51 : LANGUI_STAT_T52; ?>">
</a>
<?php
}
?>
</td><td>
<?php
if ( $this->dataList->row['player_type'] == PLAYERTYPE_NORMAL )
{
 ?>
<a onclick="return confirmDel('
<?php echo htmlspecialchars( str_replace( "'", "`", $this->dataList->row['name'] ) ); ?>
');" href="statistics.php?_dp=<?php echo $this->dataList->row['id'].( 0 < $this->_tb ? "&tb=".$this->_tb : "" ).( 0 < $this->pageIndex ? "&p=".$this->pageIndex : "" ); ?>">
<img class="del" src="assets/x.gif" alt="<?php echo LANGUI_STAT_T19; ?>" title="<?php echo LANGUI_STAT_T19; ?>">
</a>
<?php
}
?>
</td>
<?php
  }
  ?>
</tr>
<?php
 }
 ?>
 </tbody>
</table>
<table cellpadding="1" cellspacing="1" id="search_navi">
<tbody>
<tr>
<td>
<form method="post" action="statistics.php
<?php
 if ( 0 < $this->selectedTabIndex )
 {
  ?>
?t=".$this->selectedTabIndex;
 }
 else if ( 0 < $this->_tb )
 {
  ?>
?tb=".$this->_tb;
 }
 ?>">
<div class="search">
<span>:
<?php echo LANGUI_STAT_T20; ?>
<input type="text" class="text ra" maxlength="5" name="rank" value="<?php
 if ( 0 < $this->selectedRank )
 {
  echo $this->selectedRank;
 }
 ?>">
</span>
<span class="or">
<?php echo text_or_lang; ?>
</span>
<span>
<?php echo LANGUI_STAT_T21; ?>
<input type="text" class="text name" maxlength="20" name="name" value="">
</span>
<input type="image" value="submit" name="submit" id="btn_ok" class="dynamic_img" src="assets/x.gif" alt="<?php echo text_okdone_lang; ?>">
</div>
</form>
<div class="navi">
<?php echo $this->getPreviousLink( ); ?>
|
<?php echo $this->getNextLink( ); ?>
</div>
</td>
</tr>
</tbody>
</table>
<?php
}
else if ( $this->selectedTabIndex == 1 )
{
 ?>
<table cellpadding="1" cellspacing="1" id="alliance" class="row_table_data">
<thead>
<tr>
<th colspan="4">
<?php echo LANGUI_STAT_T22; ?>
<div id="submenu">
<a title="<?php echo LANGUI_STAT_T10; ?>" href="statistics.php?t=8">
<img class="btn_top10" src="assets/x.gif" alt="<?php echo LANGUI_STAT_T10; ?>">
</a>
<a title="<?php echo LANGUI_STAT_T11; ?>" href="statistics.php?t=9">
<img class="btn_def" src="assets/x.gif" alt="<?php echo LANGUI_STAT_T11; ?>">
</a>
<a title="<?php echo LANGUI_STAT_T12; ?>" href="statistics.php?t=10">
<img class="btn_off" src="assets/x.gif" alt="<?php echo LANGUI_STAT_T12; ?>">
</a>
</div>
</th>
</tr>
<tr>
<td>
</td>
<td>
<?php echo LANGUI_STAT_T13; ?>
</td>
<td>
<?php echo LANGUI_STAT_T2; ?>
</td>
<td>
<?php echo LANGUI_STAT_T23; ?>
</td>
</tr>
</thead>
<tbody>
<?php
 $rowIndex = 0;
 while ( $this->dataList->next( ) )
 {
  ++$rowIndex;
  $rank = $rowIndex + $this->pageIndex * $this->pageSize;
  ?>
<tr
<?php
  if ( $this->selectedRank == $rank )
  {
?>
 class="hl"<?php
  }
  ?>
><td class="ra">
<?php
  echo $rank;
  ?>.</td><td class="al">
<a href="alliance.php?id=<?php
  echo $this->dataList->row['id'];
  ?>">
<?php
  echo $this->dataList->row['name'];
  ?>
</a>
</td><td class="pla">
<?php
  echo $this->dataList->row['player_count'];
  ?>
</td><td class="po">
<?php
  echo $this->dataList->row['rating'];
  ?>
</td>
</tr>
<?php
 }
 ?>
 </tbody>
</table>
<table cellpadding="1" cellspacing="1" id="search_navi">
<tbody>
<tr>
<td>
<form method="post" action="statistics.php
<?php
 if ( 0 < $this->selectedTabIndex )
 {
  ?>
?t=".$this->selectedTabIndex;
 }
 ?>">
<div class="search">
<span>:
<?php echo LANGUI_STAT_T20; ?>
<input type="text" class="text ra" maxlength="5" name="rank" value="<?php
 if ( 0 < $this->selectedRank )
 {
  echo $this->selectedRank;
 }
 ?>">
</span>
<span class="or">
<?php echo text_or_lang; ?>
</span>
<span>
<?php echo LANGUI_STAT_T21; ?>
<input type="text" class="text name" maxlength="20" name="name" value="">
</span>
<input type="image" value="submit" name="submit" id="btn_ok" class="dynamic_img" src="assets/x.gif" alt="<?php echo text_okdone_lang; ?>">
</div>
</form>
<div class="navi">
<?php echo $this->getPreviousLink( ); ?>
|
<?php echo $this->getNextLink( ); ?>
</div>
</td>
</tr>
</tbody>
</table>
<?php
}
else if ( $this->selectedTabIndex == 2 )
{
 if ( $this->isAdmin )
 {
  ?>
<s
<?php
  ?>
cript type="text/javascript">function openResourceSet(vid) {p = document.getElementById("ce");if (p!=null) {p.innerHTML = '<div id="_pwin" class="popup3">
<div id="drag" onmousedown="dragStart(event, \\'_pwin\\')">
</div>
<a href="#" onClick="hideManual(); return false;">
<img src="assets/x.gif" border="1" class="popup4" alt="Move">
</a>
<iframe frameborder="0" id="Frame" src="resources.php?avid='+vi
<?php
  ?>
d+'" width="412" height="440" border="0">
</iframe>
</div>';}return false;}</script>
<?php
 }
 ?>
<table cellpadding="1" cellspacing="1" id="villages" class="row_table_data">
<thead>
<tr>
<th colspan="<?php echo $this->isAdmin ? "6" : "5"; ?>">
<?php echo LANGUI_STAT_T24; ?>
</th>
</tr>
<tr>
<td>
</td>
<td>
<?php echo LANGUI_STAT_T25; ?>
</td>
<td>
<?php echo LANGUI_STAT_T2; ?>
</td>
<td>
<?php echo LANGUI_STAT_T14; ?>
</td>
<td>
<?php echo LANGUI_STAT_T26; ?>
</td>
<?php
 if ( $this->isAdmin )
 {
  ?>
<td>&nbsp;</td>
<?php
 }
 ?>
</tr>
</thead>
<tbody>
<?php
 $rowIndex = 0;
 while ( $this->dataList->next( ) )
 {
  ++$rowIndex;
  $rank = $rowIndex + $this->pageIndex * $this->pageSize;
  ?>
<tr
<?php
  if ( $this->selectedRank == $rank )
  {
?>
 class="hl"<?php
  }
  ?>
><td class="ra">
<?php
  echo $rank;
  ?>.</td><td class="vil">
<a href="village3.php?id=<?php
  echo $this->dataList->row['id'];
  ?>">
<?php
  echo $this->dataList->row['village_name'];
  ?>
</a> </td><td class="pla">
<a href="profile.php?uid=<?php
  echo $this->dataList->row['player_id'];
  ?>">
<?php
  echo $this->dataList->row['player_name'];
  ?>
</a>
</td><td class="hab">
<?php
  echo $this->dataList->row['people_count'];
  ?>
</td><td class="aligned_coords ">
<div class="cox">(
<?php
  echo $this->dataList->row['rel_x'];
  ?>
</div>
<div class="pi">|</div>
<div class="coy">
<?php
  echo $this->dataList->row['rel_y'];
  ?>
)</div>
</td>
<?php
  if ( $this->isAdmin )
  {
?>
<td class="ra">
<a href="#" onclick="return openResourceSet(
<?php echo $this->dataList->row['id']; ?>
);">
<img src="assets/x.gif" class="r4" alt="<?php echo LANGUI_STAT_T27; ?>" title="<?php echo LANGUI_STAT_T27; ?>">
</a>
</td>
<?php
  }
  ?>
</tr>
<?php
 }
 ?>
 </tbody>
</table>
<table cellpadding="1" cellspacing="1" id="search_navi">
<tbody>
<tr>
<td>
<form method="post" action="statistics.php
<?php
 if ( 0 < $this->selectedTabIndex )
 {
  ?>
?t=".$this->selectedTabIndex;
 }
 ?>">
<div class="search">
<span>:
<?php echo LANGUI_STAT_T20; ?>
<input type="text" class="text ra" maxlength="5" name="rank" value="<?php
 if ( 0 < $this->selectedRank )
 {
  echo $this->selectedRank;
 }
 ?>">
</span>
<span class="or">
<?php echo text_or_lang; ?>
</span>
<span>
<?php echo LANGUI_STAT_T21; ?>
<input type="text" class="text name" maxlength="20" name="name" value="">
</span>
<input type="image" value="submit" name="submit" id="btn_ok" class="dynamic_img" src="assets/x.gif" alt="<?php echo text_okdone_lang; ?>">
</div>
</form>
<div class="navi">
<?php echo $this->getPreviousLink( ); ?>
|
<?php echo $this->getNextLink( ); ?>
</div>
</td>
</tr>
</tbody>
</table>
<?php
}
else if ( $this->selectedTabIndex == 3 )
{
 ?>
<table cellpadding="1" cellspacing="1" id="heroes" class="row_table_data">
<thead>
<tr>
<th colspan="5">
<?php echo LANGUI_STAT_T28; ?>
</th>
</tr>
<tr>
<td>
</td>
<td>
<?php echo LANGUI_STAT_T29; ?>
</td>
<td>
<?php echo LANGUI_STAT_T2; ?>
</td>
<td>
<?php echo level_lang2; ?>
</td>
<td>
<?php echo LANGUI_STAT_T30; ?>
</td>
</tr>
</thead>
<tbody>
<?php
 $rowIndex = 0;
 while ( $this->dataList->next( ) )
 {
  ++$rowIndex;
  $rank = $rowIndex + $this->pageIndex * $this->pageSize;
  ?>
<tr
<?php
  if ( $this->selectedRank == $rank )
  {
?>
 class="hl"<?php
  }
  ?>
><td class="ra">
<?php
  echo $rank;
  ?>.</td><td class="hero">
<img class="unit u
<?php
  echo $this->dataList->row['hero_troop_id'];
  ?>" alt="<?php
  echo constant( "troop_".$this->dataList->row['hero_troop_id'] );
  ?>" title="<?php
  echo constant( "troop_".$this->dataList->row['hero_troop_id'] );
  ?>" src="assets/x.gif"> &nbsp;
<?php
  echo $this->dataList->row['hero_name'];
  ?>
</td><td class="pla">
<a href="profile.php?uid=<?php
  echo $this->dataList->row['id'];
  ?>">
<?php
  echo $this->dataList->row['name'];
  ?>
</a>
</td><td class="lev">
<?php
  echo $this->dataList->row['hero_level'];
  ?>
</td><td class="xp">
<?php
  echo $this->dataList->row['hero_points'];
  ?>
</td>
</tr>
<?php
 }
 ?>
 </tbody>
</table>
<table cellpadding="1" cellspacing="1" id="search_navi">
<tbody>
<tr>
<td>
<form method="post" action="statistics.php
<?php
 if ( 0 < $this->selectedTabIndex )
 {
  ?>
?t=".$this->selectedTabIndex;
 }
 ?>">
<div class="search">
<span>:
<?php echo LANGUI_STAT_T20; ?>
<input type="text" class="text ra" maxlength="5" name="rank" value="<?php
 if ( 0 < $this->selectedRank )
 {
  echo $this->selectedRank;
 }
 ?>">
</span>
<span class="or">
<?php echo text_or_lang; ?>
</span>
<span>
<?php echo LANGUI_STAT_T21; ?>
<input type="text" class="text name" maxlength="20" name="name" value="">
</span>
<input type="image" value="submit" name="submit" id="btn_ok" class="dynamic_img" src="assets/x.gif" alt="<?php echo text_okdone_lang; ?>">
</div>
</form>
<div class="navi">
<?php echo $this->getPreviousLink( ); ?>
|
<?php echo $this->getNextLink( ); ?>
</div>
</td>
</tr>
</tbody>
</table>
<?php
}
else if ( $this->selectedTabIndex == 11 )
{
 ?>
<table cellpadding="1" cellspacing="1" id="villages" class="row_table_data">
<thead>
<tr>
<th colspan="5">
<?php echo LANGUI_STAT_T24; ?>
</th>
</tr>
<tr>
<td>
</td>
<td>
<?php echo LANGUI_STAT_T2; ?>
</td>
<td>
<?php echo LANGUI_STAT_T25; ?>
</td>
<td>
<?php echo LANGUI_STAT_T13; ?>
</td>
<td>
<?php echo level_lang; ?>
</td>
</tr>
</thead>
<tbody>
<?php
 $rowIndex = 0;
 while ( $this->dataList->next( ) )
 {
  ++$rowIndex;
  ?>
<tr><td class="ra">
<?php
  echo $rowIndex;
  ?>.</td><td class="pla">
<a href="profile.php?uid=<?php
  echo $this->dataList->row['player_id'];
  ?>">
<?php
  echo $this->dataList->row['player_name'];
  ?>
</a>
</td><td class="vil">
<a href="village3.php?id=<?php
  echo $this->dataList->row['id'];
  ?>">
<?php
  echo $this->dataList->row['village_name'];
  ?>
</a> </td><td class="vil">
<?php
  if ( 0 < intval( $this->dataList->row['alliance_id'] ) )
  {
?>
<a href="alliance.php?id=<?php echo $this->dataList->row['alliance_id']; ?>">
<?php echo $this->dataList->row['alliance_name']; ?>
</a>
<?php
  }
  ?>
</td><td class="ra" style="text-align:center;">
<?php
  echo $this->getWonderLandLevel( $this->dataList->row['buildings'] );
  ?>
</td>
</tr>
<?php
 }
 ?>
 </tbody>
</table>
<?php
}
else if ( $this->selectedTabIndex == 4 )
{
 ?>
<table cellpadding="1" cellspacing="1" id="world_player" class="world">
<thead>
<tr>
<th colspan="2">
<?php echo LANGUI_STAT_T2; ?>
</th>
</tr>
</thead>
<tbody>
<tr>
<th>
<?php echo LANGUI_STAT_T31; ?>
</th>
<td>
<?php echo $this->generalData['players_count']; ?>
</td>
</tr>
<tr>
<th>
<?php echo LANGUI_STAT_T32; ?>
</th>
<td>
<?php echo $this->generalData['active_players_count']; ?>
</td>
</tr>
<tr>
<th>
<?php echo LANGUI_STAT_T33; ?>
</th>
<td>
<?php echo $this->generalData['online_players_count']; ?>
</td>
</tr>
</tbody>
</table>
<table cellpadding="1" cellspacing="1" id="world_tribes" class="world">
<thead>
<tr>
<th colspan="3">
<?php echo LANGUI_STAT_T34; ?>
</th>
</tr>
<tr>
<td>
<?php echo LANGUI_STAT_T49; ?>
</td>
<td>
<?php echo LANGUI_STAT_T35; ?>
</td>
<td>
<?php echo LANGUI_STAT_T36; ?>
</td>
</tr>
</thead>
<tbody>
<tr>
<td>
<?php echo tribe_6; ?>
</td>
<td>
<?php echo $this->generalData['Dboor_players_count']; ?>
</td>
<td>
<?php echo round( $this->generalData['Dboor_players_count'] / $this->generalData['players_count'] * 100, 2 ); ?>
</td>
</tr>
<tr>
<td>
<?php echo tribe_7; ?>
</td>
<td>
<?php echo $this->generalData['Arab_players_count']; ?>
</td>
<td>
<?php echo round( $this->generalData['Arab_players_count'] / $this->generalData['players_count'] * 100, 2 ); ?>
</td>
</tr>
<tr>
<td>
<?php echo tribe_1; ?>
</td>
<td>
<?php echo $this->generalData['Roman_players_count']; ?>
</td>
<td>
<?php echo round( $this->generalData['Roman_players_count'] / $this->generalData['players_count'] * 100, 2 ); ?>
</td>
</tr>
<tr>
<td>
<?php echo tribe_2; ?>
</td>
<td>
<?php echo $this->generalData['Teutonic_players_count']; ?>
</td>
<td>
<?php echo round( $this->generalData['Teutonic_players_count'] / $this->generalData['players_count'] * 100, 2 ); ?>
</td>
</tr>
<tr>
<td>
<?php echo tribe_3; ?>
</td>
<td>
<?php echo $this->generalData['Gallic_players_count']; ?>
</td>
<td>
<?php echo round( $this->generalData['Gallic_players_count'] / $this->generalData['players_count'] * 100, 2 ); ?>
</td>
</tr>
</tbody>
</table>
<?php
}
else if ( $this->selectedTabIndex == 6 || $this->selectedTabIndex == 7 )
{
 ?>
<table cellpadding="1" cellspacing="1" id="player_off" class="row_table_data">
<thead>
<tr>
<th colspan="5">
<?php
 if ( $this->selectedTabIndex == 6 )
 {
  echo LANGUI_STAT_T37;
 }
 else
 {
  echo LANGUI_STAT_T38;
 }
 ?>
<div id="submenu">
<a title="<?php echo LANGUI_STAT_T10; ?>" href="statistics.php?t=5">
<img class="btn_top10" src="assets/x.gif" alt="<?php echo LANGUI_STAT_T10; ?>">
</a>
<a title="<?php echo LANGUI_STAT_T11; ?>" href="statistics.php
<?php echo $this->selectedTabIndex == 6 ? "" : "?t=6"; ?>">
<img class="<?php echo $this->selectedTabIndex == 6 ? "active btn_def" : "btn_def"; ?>" src="assets/x.gif" alt="<?php echo LANGUI_STAT_T11; ?>">
</a>
<a title="<?php echo LANGUI_STAT_T12; ?>" href="statistics.php
<?php echo $this->selectedTabIndex == 7 ? "" : "?t=7"; ?>">
<img class="<?php echo $this->selectedTabIndex == 7 ? "active btn_off" : "btn_off"; ?>" src="assets/x.gif" alt="<?php echo LANGUI_STAT_T12; ?>">
</a>
</div>
<div id="submenu2">
<a title="<?php echo tribe_6; ?>" href="<?php echo $this->_tb != 6 ? "?tb=6" : "?"; ?>">
<img class="<?php
 if ( $this->_tb == 6 )
 {
  ?>active <?php
 }
 ?>btn_v6" src="assets/x.gif" alt="<?php echo LANGUI_STAT_T12; ?>">
</a>
<a title="<?php echo tribe_7; ?>" href="<?php echo $this->_tb != 7 ? "?tb=7" : "?"; ?>">
<img class="<?php
 if ( $this->_tb == 7 )
 {
  ?>active <?php
 }
 ?>btn_v7" src="assets/x.gif" alt="<?php echo LANGUI_STAT_T12; ?>">
</a>
<a title="<?php echo tribe_1; ?>" href="<?php echo $this->_tb != 1 ? "?tb=1" : "?"; ?>">
<img class="<?php
 if ( $this->_tb == 1 )
 {
  ?>active 
<?php
 }
 ?>btn_v1" src="assets/x.gif" alt="<?php echo LANGUI_STAT_T12; ?>">
</a>
<a title="<?php echo tribe_2; ?>" href="<?php echo $this->_tb != 2 ? "?tb=2" : "?"; ?>">
<img class="<?php
 if ( $this->_tb == 2 )
 {
  ?>active <?php
 }
 ?>btn_v2" src="assets/x.gif" alt="<?php echo LANGUI_STAT_T12; ?>">
</a>
<a title="<?php echo tribe_3; ?>" href="<?php echo $this->_tb != 3 ? "?tb=3" : "?"; ?>">
<img class="<?php
 if ( $this->_tb == 3 )
 {
  ?>active <?php
 }
 ?>btn_v3" src="assets/x.gif" alt="<?php echo LANGUI_STAT_T12; ?>">
</a>
</div>
</th>
</tr>
<tr>
<td>
</td>
<td>
<?php echo LANGUI_STAT_T2; ?>
</td>
<td>
<?php echo LANGUI_STAT_T14; ?>
</td>
<td>
<?php echo LANGUI_STAT_T4; ?>
</td>
<td>
<?php echo LANGUI_STAT_T23; ?>
</td>
</tr>
</thead>
<tbody>
<?php
 $rowIndex = 0;
 while ( $this->dataList->next( ) )
 {
  ++$rowIndex;
  $rank = $rowIndex + $this->pageIndex * $this->pageSize;
  ?>
<tr
<?php
  if ( $this->selectedRank == $rank )
  {
?>
 class="hl"<?php
  }
  ?>
><td class="ra">
<?php
  echo $rank;
  ?>.</td><td class="pla">
<a href="profile.php?uid=<?php
  echo $this->dataList->row['id'];
  ?>">
<?php
  echo $this->dataList->row['name'];
  ?>
</a> </td><td class="pop">
<?php
  echo $this->dataList->row['total_people_count'];
  ?>
</td><td class="vil">
<?php
  echo $this->dataList->row['villages_count'];
  ?>
</td><td class="po">
<?php
  echo $this->dataList->row['points'];
  ?>
</td>
</tr>
<?php
 }
 ?>
 </tbody>
</table>
<table cellpadding="1" cellspacing="1" id="search_navi">
<tbody>
<tr>
<td>
<form method="post" action="statistics.php
<?php
 if ( 0 < $this->selectedTabIndex )
 {
  ?>
?t=".$this->selectedTabIndex;
 }
 ?>">
<div class="search">
<span>:
<?php echo LANGUI_STAT_T20; ?>
<input type="text" class="text ra" maxlength="5" name="rank" value="<?php
 if ( 0 < $this->selectedRank )
 {
  echo $this->selectedRank;
 }
 ?>">
</span>
<span class="or">
<?php echo text_or_lang; ?>
</span>
<span>
<?php echo LANGUI_STAT_T21; ?>
<input type="text" class="text name" maxlength="20" name="name" value="">
</span>
<input type="image" value="submit" name="submit" id="btn_ok" class="dynamic_img" src="assets/x.gif" alt="<?php echo text_okdone_lang; ?>">
</div>
</form>
<div class="navi">
<?php echo $this->getPreviousLink( ); ?>
|
<?php echo $this->getNextLink( ); ?>
</div>
</td>
</tr>
</tbody>
</table>
<?php
}
else if ( $this->selectedTabIndex == 9 || $this->selectedTabIndex == 10 )
{
 ?>
<table cellpadding="1" cellspacing="1" id="alliance" class="row_table_data">
<thead>
<tr>
<th colspan="4">
<?php
 if ( $this->selectedTabIndex == 9 )
 {
  echo LANGUI_STAT_T39;
 }
 else
 {
  echo LANGUI_STAT_T40;
 }
 ?>
<div id="submenu">
<a title="<?php echo LANGUI_STAT_T10; ?>" href="statistics.php?t=8">
<img class="btn_top10" src="assets/x.gif" alt="<?php echo LANGUI_STAT_T10; ?>">
</a>
<a title="<?php echo LANGUI_STAT_T11; ?>" href="statistics.php?<?php echo $this->selectedTabIndex == 9 ? "t=1" : "t=9"; ?>">
<img class="<?php
 if ( $this->selectedTabIndex == 9 )
 {
  ?>active <?php
 }
 ?>btn_def" src="assets/x.gif" alt="<?php echo LANGUI_STAT_T11; ?>">
</a>
<a title="<?php echo LANGUI_STAT_T12; ?>" href="statistics.php?<?php echo $this->selectedTabIndex == 10 ? "t=1" : "t=10"; ?>">
<img class="<?php
 if ( $this->selectedTabIndex == 10 )
 {
  ?>active <?php
 }
 ?>btn_off" src="assets/x.gif" alt="<?php echo LANGUI_STAT_T12; ?>">
</a>
</div>
</th>
</tr>
<tr>
<td>
</td>
<td>
<?php echo LANGUI_STAT_T13; ?>
</td>
<td>
<?php echo LANGUI_STAT_T2; ?>
</td>
<td>
<?php echo LANGUI_STAT_T23; ?>
</td>
</tr>
</thead>
<tbody>
<?php
 $rowIndex = 0;
 while ( $this->dataList->next( ) )
 {
  ++$rowIndex;
  $rank = $rowIndex + $this->pageIndex * $this->pageSize;
  ?>
<tr
<?php
  if ( $this->selectedRank == $rank )
  {
?>
 class="hl"<?php
  }
  ?>
><td class="ra">
<?php
  echo $rank;
  ?>.</td><td class="al">
<a href="alliance.php?id=<?php
  echo $this->dataList->row['id'];
  ?>">
<?php
  echo $this->dataList->row['name'];
  ?>
</a>
</td><td class="pla">
<?php
  echo $this->dataList->row['player_count'];
  ?>
</td><td class="po">
<?php
  echo $this->dataList->row['points'];
  ?>
</td>
</tr>
<?php
 }
 ?>
 </tbody>
</table>
<table cellpadding="1" cellspacing="1" id="search_navi">
<tbody>
<tr>
<td>
<form method="post" action="statistics.php
<?php
 if ( 0 < $this->selectedTabIndex )
 {
  ?>
?t=".$this->selectedTabIndex;
 }
 ?>">
<div class="search">
<span>:
<?php echo LANGUI_STAT_T20; ?>
<input type="text" class="text ra" maxlength="5" name="rank" value="<?php
 if ( 0 < $this->selectedRank )
 {
  echo $this->selectedRank;
 }
 ?>">
</span>
<span class="or">
<?php echo text_or_lang; ?>
</span>
<span>
<?php echo LANGUI_STAT_T21; ?>
<input type="text" class="text name" maxlength="20" name="name" value="">
</span>
<input type="image" value="submit" name="submit" id="btn_ok" class="dynamic_img" src="assets/x.gif" alt="<?php echo text_okdone_lang; ?>">
</div>
</form>
<div class="navi">
<?php echo $this->getPreviousLink( ); ?>
|
<?php echo $this->getNextLink( ); ?>
</div>
</td>
</tr>
</tbody>
</table>
<?php
}
else if ( $this->selectedTabIndex == 5 || $this->selectedTabIndex == 8 )
{
 ?>
<table cellpadding="1" cellspacing="1">
<thead>
<tr>
<th>
<?php
 if ( $this->selectedTabIndex == 5 )
 {
  echo LANGUI_STAT_T41;
 }
 else
 {
  echo LANGUI_STAT_T42;
 }
 ?>
<div id="submenu">
<a title="<?php echo LANGUI_STAT_T10; ?>" href="statistics.php<?php echo $this->selectedTabIndex == 5 ? "" : "?t=1"; ?>">
<img class="active btn_top10" src="assets/x.gif" alt="<?php echo LANGUI_STAT_T10; ?>">
</a>
<a title="<?php echo LANGUI_STAT_T11; ?>" href="statistics.php?t=<?php echo $this->selectedTabIndex == 5 ? 6 : 9; ?>">
<img class="btn_def" src="assets/x.gif" alt="<?php echo LANGUI_STAT_T11; ?>">
</a>
<a title="<?php echo LANGUI_STAT_T12; ?>" href="statistics.php?t=<?php echo $this->selectedTabIndex == 5 ? 7 : 10; ?>">
<img class="btn_off" src="assets/x.gif" alt="<?php echo LANGUI_STAT_T12; ?>">
</a>
</div>
<?php
 if ( $this->selectedTabIndex == 5 )
 {
  ?>
<div id="submenu2">
<a title="<?php
  echo tribe_6;
  ?>" href="<?php echo $this->_tb != 6 ? "?tb=6" : "?"; ?>">
<img class="<?php
  if ( $this->_tb == 6 )
  {
?>active <?php
  }
  ?>btn_v6" src="assets/x.gif" alt="<?php
  echo LANGUI_STAT_T12;
  ?>">
</a>
<a title="<?php
  echo tribe_7;
  ?>" href="<?php
  echo $this->_tb != 7 ? "?tb=7" : "?"; ?>
<?php
  ?>">
<img class="<?php
  if ( $this->_tb == 7 )
  {
?>active <?php
  }
  ?>btn_v7" src="assets/x.gif" alt="<?php
  echo LANGUI_STAT_T12;
  ?>">
</a>
<a title="<?php
  echo tribe_1;
  ?>" href="<?php
  echo $this->_tb != 1 ? "?tb=1" : "?"; ?>
<?php
  ?>">
<img class="<?php
  if ( $this->_tb == 1 )
  {
?>active <?php
  }
  ?>btn_v1" src="assets/x.gif" alt="<?php
  echo LANGUI_STAT_T12;
  ?>">
</a>
<a title="<?php
  echo tribe_2;
  ?>" href="<?php
  echo $this->_tb != 2 ? "?tb=2" : "?"; ?>
<?php
  ?>">
<img class="<?php
  if ( $this->_tb == 2 )
  {
?>active <?php
  }
  ?>btn_v2" src="assets/x.gif" alt="<?php
  echo LANGUI_STAT_T12;
  ?>">
</a>
<a title="<?php
  echo tribe_3;
  ?>" href="<?php
  echo $this->_tb != 3 ? "?tb=3" : "?"; ?>
<?php
  ?>">
<img class="<?php
  if ( $this->_tb == 3 )
  {
?>active <?php
  }
  ?>btn_v3" src="assets/x.gif" alt="<?php
  echo LANGUI_STAT_T12;
  ?>">
</a>
</div>
<?php
 }
 ?>
</th>
</tr>
</thead>
</table>
<table cellpadding="1" cellspacing="1" id="top10_offs" class="top10 row_table_data">
<thead>
<tr>
<th>
<a href="#" onclick="return showManual(6,<?php echo $this->selectedTabIndex == 5 ? 0 : 1; ?>);">
<img class="help" src="assets/x.gif" alt="<?php echo LANGUI_STAT_T43; ?>" title="<?php echo LANGUI_STAT_T43; ?>">
</a>
</th>
<th colspan="2">
<?php echo LANGUI_STAT_T44; ?>
</th>
</tr>
<tr>
<td>
<?php echo LANGUI_STAT_T20; ?>
</td>
<td>
<?php
 if ( $this->selectedTabIndex == 5 )
 {
  echo LANGUI_STAT_T2;
 }
 else
 {
  echo LANGUI_STAT_T13;
 }
 ?>
</td>
<td>
<?php echo LANGUI_STAT_T23; ?>
</td>
</tr>
</thead>
<tbody>
<?php
 $_c = 0;
 while ( $this->top10Result['ATTACK']->next( ) )
 {
  ++$_c;
  ?>
<tr
<?php
  if ( $this->top10Result['TARGETID'] == $this->top10Result['ATTACK']->row['id'] )
  {
?>
 class="hl"<?php
  }
  ?>
>
<td class="ra fc">
<?php
  echo $_c;
  ?>.&nbsp;</td>
<td class="pla">
<a href="<?php
  echo $this->top10Result['URL'].$this->top10Result['ATTACK']->row['id'];
  ?>">
<?php
  echo $this->top10Result['ATTACK']->row['name'];
  ?>
</a>
</td>
<td class="val lc">
<?php
  echo $this->top10Result['ATTACK']->row['points'];
  ?>
</td>
</tr>
<?php
 }
 ?>
 <tr>
<td colspan="3" class="empty">
</td>
</tr>  <tr class="own hl">
<td class="ra fc">?</td>
<td class="pla">
<a href="<?php echo $this->top10Result['URL'].$this->top10Result['TARGETID']; ?>">
<?php echo $this->top10Result['TARGETNAME']; ?>
</a>
</td>
<td class="val lc">
<?php echo $this->top10Result['TARGEPOINT_ATTACK']; ?>
</td>
</tr>
</tbody>
</table>
<table cellpadding="1" cellspacing="1" id="top10_defs" class="top10 row_table_data">
<thead>
<tr>
<th>
<a href="#" onclick="return showManual(6,
<?php echo $this->selectedTabIndex == 5 ? 0 : 1; ?>
);">
<img class="help" src="assets/x.gif" alt="<?php echo LANGUI_STAT_T43; ?>" title="<?php echo LANGUI_STAT_T43; ?>">
</a>
</th>
<th colspan="2">
<?php echo LANGUI_STAT_T45; ?>
</th>
</tr>
<tr>
<td>
<?php echo LANGUI_STAT_T20; ?>
</td>
<td>
<?php
 if ( $this->selectedTabIndex == 5 )
 {
  echo LANGUI_STAT_T2;
 }
 else
 {
  echo LANGUI_STAT_T13;
 }
 ?>
</td>
<td>
<?php echo LANGUI_STAT_T23; ?>
</td>
</tr>
</thead>
<tbody>
<?php
 $_c = 0;
 while ( $this->top10Result['DEFENSE']->next( ) )
 {
  ++$_c;
  ?>
<tr
<?php
  if ( $this->top10Result['TARGETID'] == $this->top10Result['DEFENSE']->row['id'] )
  {
?>
 class="hl"<?php
  }
  ?>
>
<td class="ra fc">
<?php
  echo $_c;
  ?>.&nbsp;</td>
<td class="pla">
<a href="<?php
  echo $this->top10Result['URL'].$this->top10Result['DEFENSE']->row['id'];
  ?>">
<?php
  echo $this->top10Result['DEFENSE']->row['name'];
  ?>
</a>
</td>
<td class="val lc">
<?php
  echo $this->top10Result['DEFENSE']->row['points'];
  ?>
</td>
</tr>
<?php
 }
 ?>
 <tr>
<td colspan="3" class="empty">
</td>
</tr>  <tr class="own hl">
<td class="ra fc">?</td>
<td class="pla">
<a href="<?php echo $this->top10Result['URL'].$this->top10Result['TARGETID']; ?>">
<?php echo $this->top10Result['TARGETNAME']; ?>
</a>
</td>
<td class="val lc">
<?php echo $this->top10Result['TARGEPOINT_DEFENSE']; ?>
</td>
</tr>
</tbody>
</table>
<div class="clear">
</div>
<table cellpadding="1" cellspacing="1" id="top10_climbers" class="top10 row_table_data">
<thead>
<tr>
<th>
<a href="#" onclick="return showManual(6,
<?php echo $this->selectedTabIndex == 5 ? 0 : 1; ?>
);">
<img class="help" src="assets/x.gif" alt="<?php echo LANGUI_STAT_T43; ?>" title="<?php echo LANGUI_STAT_T43; ?>">
</a>
</th>
<th colspan="2">
<?php echo LANGUI_STAT_T46; ?>
</th>
</tr>
<tr>
<td>
<?php echo LANGUI_STAT_T20; ?>
</td>
<td>
<?php
 if ( $this->selectedTabIndex == 5 )
 {
  echo LANGUI_STAT_T2;
 }
 else
 {
  echo LANGUI_STAT_T13;
 }
 ?>
</td>
<td>
<?php echo LANGUI_STAT_T50; ?>
</td>
</tr>
</thead>
<tbody>
<?php
 $_c = 0;
 while ( $this->top10Result['DEV']->next( ) )
 {
  ++$_c;
  ?>
<tr
<?php
  if ( $this->top10Result['TARGETID'] == $this->top10Result['DEV']->row['id'] )
  {
?>
 class="hl"<?php
  }
  ?>
>
<td class="ra fc">
<?php
  echo $_c;
  ?>.&nbsp;</td>
<td class="pla">
<a href="<?php
  echo $this->top10Result['URL'].$this->top10Result['DEV']->row['id'];
  ?>">
<?php
  echo $this->top10Result['DEV']->row['name'];
  ?>
</a>
</td>
<td class="val lc">
<?php
  echo $this->top10Result['DEV']->row['points'];
  ?>
</td>
</tr>
<?php
 }
 ?>
 <tr>
<td colspan="3" class="empty">
</td>
</tr>  <tr class="own hl">
<td class="ra fc">?</td>
<td class="pla">
<a href="<?php echo $this->top10Result['URL'].$this->top10Result['TARGETID']; ?>">
<?php echo $this->top10Result['TARGETNAME']; ?>
</a>
</td>
<td class="val lc">
<?php echo $this->top10Result['TARGEPOINT_DEV']; ?>
</td>
</tr>
</tbody>
</table>
<table cellpadding="1" cellspacing="1" id="top10_raiders" class="top10 row_table_data">
<thead>
<tr>
<th>
<a href="#" onclick="return showManual(6,
<?php echo $this->selectedTabIndex == 5 ? 0 : 1; ?>
);">
<img class="help" src="assets/x.gif" alt="<?php echo LANGUI_STAT_T43; ?>" title="<?php echo LANGUI_STAT_T43; ?>">
</a>
</th>
<th colspan="2">
<?php echo LANGUI_STAT_T47; ?>
</th>
</tr>
<tr>
<td>
<?php echo LANGUI_STAT_T20; ?>
</td>
<td>
<?php
 if ( $this->selectedTabIndex == 5 )
 {
  echo LANGUI_STAT_T2;
 }
 else
 {
  echo LANGUI_STAT_T13;
 }
 ?>
</td>
<td>
<?php echo LANGUI_STAT_T48; ?>
</td>
</tr>
</thead>
<tbody>
<?php
 $_c = 0;
 while ( $this->top10Result['THIEF']->next( ) )
 {
  ++$_c;
  ?>
<tr
<?php
  if ( $this->top10Result['TARGETID'] == $this->top10Result['THIEF']->row['id'] )
  {
?>
 class="hl"<?php
  }
  ?>
>
<td class="ra fc">
<?php
  echo $_c;
  ?>.&nbsp;</td>
<td class="pla">
<a href="<?php
  echo $this->top10Result['URL'].$this->top10Result['THIEF']->row['id'];
  ?>">
<?php
  echo $this->top10Result['THIEF']->row['name'];
  ?>
</a>
</td>
<td class="val lc">
<?php
  echo $this->top10Result['THIEF']->row['points'];
  ?>
</td>
</tr>
<?php
 }
 ?>
 <tr>
<td colspan="3" class="empty">
</td>
</tr>  <tr class="own hl">
<td class="ra fc">?</td>
<td class="pla">
<a href="<?php echo $this->top10Result['URL'].$this->top10Result['TARGETID']; ?>">
<?php echo $this->top10Result['TARGETNAME']; ?>
</a>
</td>
<td class="val lc">
<?php echo $this->top10Result['TARGEPOINT_THIEF']; ?>
</td>
</tr>
</tbody>
</table>
<?php
}
?>